language: java
jdk: openjdk7

# skip default install step
install: true

# codecov
before_script:
  - pip install --user codecov

# build
script: mvn clean install -Dsnapshot.version=-`git rev-parse --short HEAD`

after_success:
 - bash -x -e .travis/deploy.sh
 - codecov

#notifications:
#  irc:
#  - irc.freenode.org#pircbotx
