language: java
jdk: oraclejdk8
after_success:
 #Deploy snapshot to sonatype
 - mvn deploy --settings .travis/maven-settings.xml
 #Deploy javadoc to gh-pages branch
 - mvn site site-deploy -Pcomplete-build
 - git checkout gh-pages
 - cd latest && rm -rf * && mv ../target/site-deploy-generated/* .
 - git add .
 - GIT_AUTHOR_NAME="Leon Blakey" GIT_AUTHOR_EMAIL=leon.m.blakey@gmail.com git commit -m "Autobuild of maven site"
 - git push https://$DEPLOY_PAGES_USERNAME:$DEPLOY_PAGES_PASSWORD@github.com/TheLQ/pircbotx.git
notifications:
  irc:
  - irc.freenode.org#pircbotx