language: java
jdk: openjdk7

# skip default install step
install: true

# codecov
before_script:
  - pip install --user codecov

# build
script: mvn --batch-mode clean install -Dsnapshot.version=-`git rev-parse --short HEAD`

after_success:
 - mvn source:jar --batch-mode deploy --settings .travis/maven-settings.xml
 - codecov
# - bash -x -e .travis/deploy.sh


#notifications:
#  irc:
#  - irc.freenode.org#pircbotx
