language: java
jdk: oraclejdk8
after_success:
 #Always skip tests after here, as they already ran and can cause the output to exceed travis's maximum log length
 #Deploy snapshot to sonatype
 - mvn deploy -DskipTests=true --settings .travis/maven-settings.xml
 #Deploy javadoc to gh-pages branch
 - mvn site site-deploy -Pcomplete-build -DskipTests=true --batch-mode
 - git clone --depth=50 --branch=master git://github.com/TheLQ/pircbotx.git pircbotx.site
 - cd pircbotx.site/latest
 - rm -rf *
 - mv ../../target/site-deploy-generated/* .
 - git add -A
 - git config user.name "Leon Blakey"
 - git config user.email "leon.m.blakey@gmail.com"
 - git commit -m "Autobuild of maven site"
 - git push https://$DEPLOY_PAGES_USERNAME:$DEPLOY_PAGES_PASSWORD@github.com/TheLQ/pircbotx.git
notifications:
  irc:
  - irc.freenode.org#pircbotx