language: java
jdk: openjdk7

# skip default install step
install: true

# codecov
before_script:
  - pip install --user codecov

# build
script: mvn clean install -Dsnapshot.version=-`git rev-parse --short HEAD`

after_success:
 - codecov

deploy:
  provider: script
  script: .travis/deploy.sh

#notifications:
#  irc:
#  - irc.freenode.org#pircbotx
