language: java
jdk: openjdk7

# skip default install step
install: true

# codecov
before_script:
  - pip install --user codecov

# build
script: 
  - echo -en "\ntravis_fold:start:dependencies\r"
  - mvn dependency:resolve dependency:resolve-plugins 
  - echo -en "\ntravis_fold:end:dependencies\r"
  - mvn clean install -Dsnapshot.version=-`git rev-parse --short HEAD`

after_success:
 - mvn source:jar deploy --settings .travis/maven-settings.xml
 - codecov
# - bash -x -e .travis/deploy.sh


#notifications:
#  irc:
#  - irc.freenode.org#pircbotx
